language: elixir

elixir:
  - 1.4.1

services:
  - postgresql
  
before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - rm -rf deps
  - rm -rf _build
  - mix deps.get
  - mix ecto.create
  - mix ecto.migrate

script:
  - mix test
